### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by godlesowned** [LeadBrowser/app#21]
When installing:

Migrating: 2022_10_27_214006_add_is_correct_to_emails_table

In Connection.php line 712:
                                                                                                               
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'spoof_check' in 'emails' (SQL: alter table `emails`  
   add `is_correct` tinyint(1) not null default '0' after `spoof_check`)                                       
                                                                                                               

In Connection.php line 501:
                                                                                    
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'spoof_check' in 'emails'

**Comment by mariuszmalek** [comment]
Fixed :))
